### ISSUE TITLE
有关于HITSZ LUG痛衣的购买意向调查

### ISSUE THREAD

**Issue by wold9168** [hitlug/form-collection#1]
以下统计有关于HITSZ LUG所出品的主题痛衣购买意向。

痛衣的大概预览图如下：
![图片](https://github.com/hitlug/form-collection/assets/48375098/b624b9c6-3961-4abf-934e-667204ba7a2c)

痛衣的可选尺码如下：
![图片](https://github.com/hitlug/form-collection/assets/48375098/ca435edf-8675-4d89-a9e1-3ffdd0c3cc68)

目前该物料的准备正处于众筹阶段，仅作购买意向的调查，统计本部lug群聊内有意购买者的人数。与深圳分部之统计不作重复——向深圳分部表达购买意向的，不必在本issue中作回复。

预期的分发形式是，集中邮寄到本部一校区，而后在一校区本社团社团活动室进行分发。可能采取自助领取与登记的形式。

有意购买者请在本issue中作回复或点赞（两者独立计数）。——回复时请勿透露个人隐私信息。

众筹阶段统计购买意向结束后，尺码的记录和订金的提交会另外收集和处理。

**Comment by wold9168** [comment]
HITSZ LUG方面反映预期人数达到目标。意向收集中止。
截止至目前，本帖下共有5人表露购买意向。

**Comment by billchenchina** [comment]
> 深圳分部方面反映预期人数达到目标。意向收集中止。 

不是分部

**Comment by wold9168** [comment]
> > 深圳分部方面反映预期人数达到目标。意向收集中止。
> 
> 不是分部

已经修改相关措辞。

（我以为深圳分校那边的lug可以叫分部的XD）

**Comment by Xeonacid** [comment]
> 已经修改相关措辞。

HITSZ LUG ×
HITSZ OSA ✓

**Comment by rewired-gh** [comment]
> > > 深圳分部方面反映预期人数达到目标。意向收集中止。
> > 
> > 
> > 不是分部
> 
> 已经修改相关措辞。
> 
> （我以为深圳分校那边的lug可以叫分部的XD）

以前是叫 HITSZ LUG，后来成立社团的时候一些领导觉得 Linux User Group 范畴有点狭窄，所以改名了。

另外，我们可能需要一位校本部同学负责统一代收寄往校本部的所有衣服，并且负责后续分发。这样的话，可以节省一些邮费，同时也让定制流程没那么麻烦。如果可以的话需要提供一下收件人名字和具体地址。

非常感谢！
